#!/bin/bash
echo "═══════════════════════════════════════════════════════════════"
echo "📂 CHECKING IF FILES ARE ACTUALLY IN THE DEPLOYMENT"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Check what files are actually deployed
echo "Local file structure:"
echo "---------------------"
echo "Root directory images:"
ls -1 *.png *.jpg 2>/dev/null | wc -l
echo ""
echo "Public directory:"
ls -1 public/* 2>/dev/null | wc -l
echo ""
echo "Vercel deployment should include these files."
echo ""
echo "The 401 error means:"
echo "  - Files exist but server.js is blocking access"
echo "  - Need to bypass server.js for static files"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "THE REAL SOLUTION:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Option 1: Add header checks in server.js"
echo "  if (req.path.startsWith('/public/')) {"
echo "    return res.sendFile(path.join(__dirname, req.path));"
echo "  }"
echo ""
echo "Option 2: Use Vercel's cleanUrls and trailingSlash"
echo ""
echo "Option 3: Create a separate static directory build"
echo ""
echo "Run: ./bypass-server-js.sh"
echo "═══════════════════════════════════════════════════════════════"
