#!/bin/bash
echo "═══════════════════════════════════════════════════════════════"
echo "🔍 Checking Vercel deployment logs..."
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Visit: https://vercel.com/shotokanschookaratedos-projects/sskda-website"
echo ""
echo "Click on the latest deployment and check the logs."
echo ""
echo "Look for:"
echo "  ✓ Build completed successfully"
echo "  ✓ Files included in deployment"
echo "  ✓ Any errors or warnings"
echo ""
echo "The persistent 401 suggests:"
echo "  1. Authentication middleware (not in code)"
echo "  2. Vercel project settings issue"
echo "  3. Domain configuration problem"
echo ""
echo "Try redeploying from the Vercel dashboard (not CLI):"
echo "  1. Visit https://vercel.com"
echo "  2. Select your project"
echo "  3. Go to Deployments"
echo "  4. Redeploy latest"
echo "═══════════════════════════════════════════════════════════════"
