#!/bin/bash
echo "═══════════════════════════════════════════════════════════════"
echo "🔍 DIAGNOSTIC: What's actually in the Vercel deployment?"
echo "═══════════════════════════════════════════════════════════════"
echo ""

cd /home/ailove/Downloads/SSKDA_Website

echo "Local files that should be deployed:"
echo "--------------------------------------"
echo "PNG files in root: $(ls *.png 2>/dev/null | wc -l)"
echo "JPG files in root: $(ls *.jpg 2>/dev/null | wc -l)"
echo "Files in public/: $(ls public/* 2>/dev/null | wc -l)"
echo ""
echo "vercel.json includeFiles pattern:"
grep -A 10 "includeFiles" vercel.json | head -15
echo ""
echo "Routes defined:"
grep '"src"' vercel.json | head -10
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "Testing if vercel.json is even being used..."
echo "═══════════════════════════════════════════════════════════════"
test_url="https://sskda-website-33cgtx4z9-shotokanschookaratedos-projects.vercel.app/server.js"
echo "Fetching server.js directly..."
curl -s -o /dev/null -w "Status: %{http_code}\n" "$test_url"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "ACTUAL ROOT CAUSE:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "The 'builds' array in vercel.json with '@vercel/node' tells"
echo "Vercel: 'Everything goes through server.js'"
echo ""
echo "Therefore, even with routes defined, ALL requests hit server.js"
echo ""
echo "SOLUTION: Add handle: filesystem before server.js routes"
echo ""
echo "Run: ./deploy-with-handle.sh"
