#!/bin/bash
echo "╔═══════════════════════════════════════════╗"
echo "║      SSKDA Website - LAUNCH SCRIPT        ║"
echo "╚═══════════════════════════════════════════╝"
echo ""
echo "🌐 Starting local development server..."
echo ""
echo "─────────────────────────────────────────────"
echo "│  ⚠️  DATABASE SETUP REQUIRED              │"
echo "─────────────────────────────────────────────"
echo ""
echo "Open a NEW terminal window and run this:"
echo ""
echo "sudo mysql -u root -e \"CREATE DATABASE sskda_website; USE sskda_website; $(cat database/import.sql | tr '\n' ' ')\""
echo ""
echo "Or if that doesn't work, run these commands:"
echo ""
echo "sudo mysql -u root"
echo "mysql> CREATE DATABASE sskda_website;"
echo "mysql> USE sskda_website;"
echo "mysql> (paste contents of database/import.sql)"
echo "mysql> EXIT;"
echo ""
echo "─────────────────────────────────────────────"
echo ""
echo "After database setup, visit:"
echo "  Homepage: http://localhost:8000/pages/index.html"
echo "  API Test: http://localhost:8000/api/achievements.php"
echo ""
echo "Press Ctrl+C to stop the server"
echo ""
echo "─────────────────────────────────────────────"
echo "Starting PHP server..."
echo "─────────────────────────────────────────────"

php -S localhost:8000